#! /bin/sh

HTP_SERVERS="$(snapctl get hosts)"
XTRA_OPTS="$(snapctl get extra-opts)"

while ! timedatectl status >/dev/null 2>&1; do
    echo "time control interface not connected yet, please run:"
    echo "snap connect $SNAP_NAME:time-control"
    exit 0
done

htpdate -D -s $XTRA_OPTS -i "$PIDFILE" $HTP_SERVERS
