name: htpdate-daemon
base: core18
adopt-info: htpdate
summary: Receive time and date settings via http/https
description: |
 The  HTTP Time Protocol (HTP) is used to synchronize a computers time with
 web servers as reference time source. This program can be used instead
 ntpdate or similar, in networks that has a firewall blocking the NTP port.
 .
 Htpdate will synchronize the computer time to Greenwich Mean Time (GMT),
 using the timestamps from HTTP headers found in web servers response (the
 HEAD method will be used to get the information).
 .
 Htpdate works through proxy servers. Accuracy of htpdate will be usually
 within 0.5 seconds (better with multiple servers). 
 .
 To allow the snap package to adjust the time you need to connect the
 time-control interface after installation and restart the daemon:
 .
     snap connect htpdate-daemon:time-control
 .
 You can set the list of hosts (default: google.com) to query for time
 via a snap setting like:
 .
     snap set htpdate-daemon hosts="google.com www.linux.org"
 .
 You can also set additional options for the daemon
 .
     snap set htpdate-daemon extra-opts="-d"

grade: stable
confinement: strict

apps:
  htpdate:
    command: htpdate
    plugs:
      - network
      - network-bind
      - time-control
  daemon:
    command: htpdated
    daemon: forking
    reload-command: usr/bin/pkill -HUP -F $PIDFILE
    post-stop-command: bin/rm -f $PIDFILE
    environment:
      PIDFILE: "/tmp/htpdate.pid"
    plugs:
      - network
      - network-bind
      - time-control
     
parts:
  htpdate:
    plugin: make
    source: https://salsa.debian.org/debian/htpdate.git
    override-pull: |
      snapcraftctl pull
      git apply -v ../../../htpdate.patch
      snapcraftctl set-version $(grep "#define VERSION" htpdate.c|sed 's/.*[a-zA-Z\t]//;s/"//g')
    stage-packages:
      - coreutils
      - procps
  htpdated:
    plugin: nil
    source: .
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -avf htpdated $SNAPCRAFT_PART_INSTALL/bin/
